# -*- coding: utf-8 -*-
"""CNPJ_API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mqb-tYxM2EtkRsCEsfR0MLTn1ettII60
"""

import requests
import json

def buscar_dados():
    
	cnpj_input = input('Digite o número do CNPJ para a consulta: ')

	if len(cnpj_input) != 14:
		print('Quantidade de dígitos inválida!')
		exit()
    
	url = "https://api.cnpja.com.br/companies/{}".format(cnpj_input)
	headers = {'authorization': '10a7bd69-e50f-41fd-ab8b-e4aefca337e7-c54c0734-2960-4658-bba8-0558f463bbe8'}
	response = requests.request("GET", url, headers=headers) ##requests.get("http://localhost:3002/api/todo")
	todos = json.loads(response.content)
    
	if 'erro' not in todos:
		print('==> CNPJ Encontrado <==')
		print('Nome: {}'.format(todos['name']))
		print('CNPJ: {}'.format(todos['tax_id']))
		print('Natureza legal: {}'.format(todos['legal_nature']))
	##	print('Representante: {}'.format(todos['menbership name']))
	##	print(todos)
	else:
		print('{}: CNPJ inválido.'.format(cnpj_input))

	print('---------------------------------')
	option = int(input('Deseja realizar uma nova consulta ?\n1. Sim\n2. Sair\n'))
	if option == 1:
		main()
	else:
		print('Saindo...')

if __name__ == '__main__':
    buscar_dados()

